// Re-export shared email-insight logic (canonical copy in netlify/functions/lib).
export {
  isEnergyServicesEmail,
  extractAddress,
  extractDateTime,
  classifyAppointmentType,
  classifyEmailOutcome,
  appointmentTypeLabel,
  parseEmailInsight,
  matchJobForInsight,
  buildProposedActions,
  formatInsightLead,
  formatAppliedLead,
  enrichInsight,
  paperworkPatchForInsight,
  normalizeAddress,
  addressSimilarity,
  stripHtml,
  canAutoApply,
  defaultActionKeys,
  isDateTimeActionable,
  AUTO_APPLY_MIN_SCORE,
} from "../../../netlify/functions/lib/emailInsight.mjs";
