// Re-export shared email-insight logic (canonical copy in netlify/functions/lib).
export {
  isEnergyServicesEmail,
  extractAddress,
  extractDateTime,
  extractTimeWindow,
  floorToHalfHour,
  addMinutesToLocalIso,
  formatClockLabel,
  resolveScheduleTimes,
  buildAppointmentDescription,
  classifyAppointmentType,
  classifyEmailOutcome,
  appointmentTypeLabel,
  parseEmailInsight,
  matchJobForInsight,
  buildProposedActions,
  formatInsightLead,
  formatAppliedLead,
  enrichInsight,
  paperworkPatchForInsight,
  normalizeAddress,
  addressSimilarity,
  stripHtml,
  canAutoApply,
  defaultActionKeys,
  isDateTimeActionable,
  AUTO_APPLY_MIN_SCORE,
  EMAIL_INSIGHT_TEST_AUTO_APPLY_LIMIT,
  APPOINTMENT_DURATION_MINUTES,
} from "../../../netlify/functions/lib/emailInsight.mjs";
